# This is a basic workflow that is manually triggered

name: Build Dev Branch

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - dev
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: send
      run: |
        curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.DEV_PUSH_INTERNAL}}" -H "Accept: application/vnd.github.v3+json" -H "Content-Type: application/json" https://api.github.com/repos/datapolitical/cfndev.github.io/actions/workflows/test-jekyll.yml/dispatches --data '{"ref": "main"}'
