name: Update Recipes

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * *'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Execute Python script
        run: |
          python export.py

      - name: setup git config
        run: |
          git config user.name ${{ secrets.USERNAME_GITHUB }}
          git config user.email ${{ secrets.EMAIL }}
