name: Update Diary

on:
  schedule:
    - cron:  '59 * * * *'
  workflow_dispatch:

jobs:

  diary:
    runs-on: ubuntu-latest
    concurrency: diary
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: setup git config
        run: |
          git config --local user.name ${{ secrets.USERNAME_GITHUB }}
          git config --local user.email ${{ secrets.EMAIL }}
          git pull --ff-only origin main
          curl https://raw.githubusercontent.com/datapolitical/mnd-exporter/main/recent_food.yml --output _data/recent_food.yml
          git add _data/recent_food.yml
          git commit -am "Update last meal" || echo "Nothing to update"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN_RECIPES }}
          branch: ${{ github.ref }}
