name: Update Diary

on:
  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: setup git config
        run: |
          git config --local user.name ${{ secrets.USERNAME_GITHUB }}
          git config --local user.email ${{ secrets.EMAIL }}
          git pull --ff-only origin main
          curl https://github.com/datapolitical/mnd-exporter/raw/main/recent_food.txt --output recent_food.txt
          git add recent_food.txt
          git commit -am "Update last meal" || echo "Nothing to update"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN_RECIPES }}
          branch: ${{ github.ref }}
