name: Auto -> Update Diary

on:
  schedule:
    - cron:  '*/20 * * * *'
  workflow_dispatch:

jobs:

  diary:
    runs-on: ubuntu-latest
    concurrency: diary
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Execute Python script
        run: |
          python3 -m mndexp
          mv recent_food.yml _data/recent_food.yml
        env:
          MY_NET_DIARY_LOGIN: ${{ secrets.MY_NET_DIARY_LOGIN }}
          MY_NET_DIARY_PASSWORD: ${{ secrets.MY_NET_DIARY_PASSWORD }}

      - name: setup git config
        run: |
          git config --local user.name ${{ secrets.USERNAME_GITHUB }}
          git config --local user.email ${{ secrets.EMAIL }}
          git add _data/recent_food.yml
          git pull --ff-only origin main
          git commit -am "Update last meal" || echo "Nothing to update"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN_RECIPES }}
          branch: ${{ github.ref }}
