name: Deploy Jekyll

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  jekyll:
    runs-on: ubuntu-latest

    steps:

      - name: checkout main
        uses: actions/checkout@v2

      - name: checkout gh-test
        uses: actions/checkout@v2
        with:
          ref: 'gh-test'
          path: 'gh-test'

      - name: setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Clean install dependencies and build
        if: 1 == 0
        run: |
          sudo apt-get update && sudo apt-get install -y libvips42
          ldd --version

      - name: cache gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-

      # Use GitHub Actions' cache to cache site on servers
      - uses: actions/cache@v2
        with:
          path: gh-test
          key: ${{ runner.os }}-build-new-${{ hashFiles('**/_data/picture.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-new-

      - name: bundle install
        run: |
          bundle install --path=vendor/bundle --jobs 4 --retry 3

      - name: jekyll build
        run: bundle exec jekyll build --destination gh-test
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          publish_dir: ./gh-test
          publish_branch: gh-test
          force_orphan: true
          cname: www.chrisfnicholson.com