name: Deploy Jekyll

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  jekyll:
    runs-on: ubuntu-latest

    steps:

      - name: checkout main
        uses: actions/checkout@v2

      - name: checkout gh-test
        uses: actions/checkout@v2
        with:
          ref: 'gh-test'
          path: 'gh-test'

      - name: setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Clean install dependencies and build
        run: |
          sudo apt-get update && sudo apt-get install -y libvips42
          ldd --version

      - name: cache gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-

      - name: bundle install
        run: |
          gem install json
          gem install webrick
          bundle install --path=vendor/bundle --jobs 4 --retry 3
          gem uninstall ffi
          gem install ffi

      - name: jekyll build
        run: bundle exec jekyll build --destination gh-test

      - name: push gh-pages
        run: |
          cd gh-test && \
          touch .nojekyll && \
          git init && \
          git config user.name "${GITHUB_ACTOR}" && \
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com" && \
          git add . && \
          git commit -m "jekyll build from Action ${GITHUB_SHA}" && \
          git push gh-test
