name: Deploy Jekyll

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  jekyll:
    runs-on: ubuntu-latest

    steps:

      - name: checkout main
        uses: actions/checkout@v2

      - name: checkout gh-test
        uses: actions/checkout@v2
        with:
          ref: 'gh-test'
          path: 'gh-test'

      - name: setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Clean install dependencies and build
        run: |
          sudo apt-get update && sudo apt-get install -y libvips42
          ldd --version

      - name: cache gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-

      # Use GitHub Actions' cache to cache site on servers
      - uses: actions/cache@v2
        with:
          path: build
          key: ${{ runner.os }}-build-new-${{ hashFiles('**/_data/picture.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-new-

      - name: bundle install
        run: |
          gem install json
          gem install webrick
          bundle install --path=vendor/bundle --jobs 4 --retry 3

      - name: jekyll build
        run: bundle exec jekyll build --destination gh-test

      - name: setup push gh-pages
        run: |
          rm -rf .git && \
          cd gh-test && \
          rm -rf .git
          
      - name: Setup Key #webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          # Private SSH key to register in the SSH agent
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
          
      - name: push gh-pages
        run: |
          pwd
          touch .nojekyll && \
          git init && \
          git config --local user.name ${{ secrets.USERNAME_GITHUB }} && \
          git config --local user.email ${{ secrets.EMAIL }} && \
          git add . && \
          git commit -m "jekyll build from Action ${GITHUB_SHA}"
          
      - name: Push changes
        if: ${{ !env.ACT }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "gh-test"
          force: true
          directory: "gh-test"