name: Merge Main into Contrast

on:
  push:
    branches:
      - main  # Here source code branch is `master`, it could be other branch
  workflow_dispatch:

jobs:
  get_data:
    runs-on: ubuntu-latest
    concurrency: sync
    permissions:
          contents: write
          actions: write
          checks: write
    steps:
      - name: Setup Key #webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          # Private SSH key to register in the SSH agent
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: setup git config
        run: |
          git config --local user.name ${{ secrets.USERNAME_GITHUB }}
          git config --local user.email ${{ secrets.EMAIL }}
          echo "Git Setup Status:"
          git status
          # echo "SSL Key setup info"
          # ssh -vT git@github.com
          echo "Git Setup Remotes:"
          git remote -v
          git fetch
          git checkout main
          git checkout contrast
          git merge --ff-only main

      - name: commit
        run: |
          git commit -am "Sync main to contrast"
          # This should be the main commit message ideally

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: contrast
